//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_ProyectoWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuario
    {
        public int ConsecutivoUsuario { get; set; }
        public string Identificacion { get; set; }
        public string Nombre { get; set; }
        public string CorreoElectronico { get; set; }
        public string Contrasenia { get; set; }
        public bool Estado { get; set; }
        public int ConsecutivoPerfil { get; set; }
    
        public virtual tbPerfil tbPerfil { get; set; }
    }
}
